### ISSUE TITLE
The result of getSnapshot should be cached to avoid an infinite loop

### ISSUE THREAD

**Issue by branquito** [zustandjs/derive-zustand#3]
I am trying to use something similar to your example on animals & kinds, in my own project, but getting the error

`The result of getSnapshot should be cached to avoid an infinite loop`

This error appeared when I tried to return an object with multiple computed values inside the `derive` function

Here is a code excerpt:

```
const vanityMetaData = derive<VanityMetaDataStore>((get) => {
  const vanities = get(useVanityUrlStore);

  return {
    computedShortUrl: SHORT_URL_PREFIX + vanities.link.shortUrl,
    isEditing: vanities.link.id !== null,
  };
});
```

Then, I am using it in a component like this:

```
  const { isEditing, computedShortUrl } = useVanityMeta((state) => state);
```

My original store, that I am trying to get computed values from is using `immer` as a middleware, and is structured
like this:

```
export const useVanityUrlStore = create<State & Actions>()(
  immer((set) => ({
    ...initialState,
    updateModel: (key, value) =>
      set((state) => {
        state.link[key] = value;
      }),
    reset: () => {
      set(initialState);
    },
  })),
);
```

I am getting the desired behaviour, but don't know how to get rid of this warning message.

What should I do to prevent this, or this is maybe some internal thing of `derive-zustand` library?

**Comment by dai-shi** [comment]
Thanks for reporting. `derive-zustand` does nothing about this, and it's basically the zustand behavior.

Can you try this?
```js
  const isEditing = useVanityMeta((state) => state.isEditing);
  const computedShortUrl = useVanityMeta((state) => state.computedShortUrl);
```

(Otherwise, you could try caching the value in your selector, or memoize your function. But, if the above works, it's overcomplicated.)
