### ISSUE TITLE
Derived store is not update

### ISSUE THREAD

**Issue by wowblvck** [zustandjs/derive-zustand#5]
After updating to version 0.1.0, the store that accumulates other stores stopped working. This can be clearly seen in the example from [CodeSandbox](https://codesandbox.io/p/sandbox/vigorous-microservice-jnf92q?file=%2Fsrc%2FApp.tsx%3A4%2C41). Everything worked on the previous version 0.0.1.

P.S. Is there a more optimal and better solution that allows you to track changes in small stores, so that you can then collect data from them in a large store and use the data from the large store.

**Version**: 0.1.0

**Comment by dai-shi** [comment]
Thanks for reporting.
That's unexpected.
This seems working. https://stackblitz.com/github/zustandjs/derive-zustand/tree/main/examples/01_counter
Can you find any difference?

**Comment by dai-shi** [comment]
> P.S. Is there a more optimal and better solution that allows you to track changes in small stores, so that you can then collect data from them in a large store and use the data from the large store.

Well, I'd generally suggest one store in such a case.

**Comment by wowblvck** [comment]
@dai-shi  The fact of the matter is that there is no difference, but in one case it works, and in the other it does not. The same situation happened on the project, after the update it stopped working, but if you roll back to the previous version, then everything works

**Comment by dai-shi** [comment]
Interesting.
This change https://github.com/zustandjs/derive-zustand/pull/4/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80 seems to cause it. Probably caused by different React versions.

I'll dig into it.

**Comment by dai-shi** [comment]
I hope #6 fixes it.

Can you try the csb build?
https://ci.codesandbox.io/status/zustandjs/derive-zustand/pr/6
☝️ Find "Local Install Instructions"

**Comment by wowblvck** [comment]
> I hope #6 fixes it.
> 
> Can you try the csb build? https://ci.codesandbox.io/status/zustandjs/derive-zustand/pr/6 ☝️ Find "Local Install Instructions"

I apologize for the long response. Yes, it works. At first glance, this update does not seem to cause any problems.

**Comment by wowblvck** [comment]
> > P.S. Is there a more optimal and better solution that allows you to track changes in small stores, so that you can then collect data from them in a large store and use the data from the large store.
> 
> Well, I'd generally suggest one store in such a case.

Yes, it seems that one store is the right way to go, BUT this one store will contain a huge number of states, which, it seems to me, is not very convenient from an architectural and development point of view.
